### PR TITLE
Fix Poco build

### LINKED ISSUE #37: Deployment example broken with Poco library
https://travis-ci.org/conan-io/examples/builds/618518029

### PR DESCRIPTION
**Pull request by uilianries**
fixes #37 

/cc @danimtb

### CODE REVIEW

**Comment by danimtb** [comment]
@uilianries please check the examples in the documentation and open a PR to reflect the same changes done here. Add also a note in the getting started indicating that the examples are prepared to run on the latest Conan version

**Comment by uilianries** [comment]
I'm curious, should I update ALL old packages from Conan Center and replace with those listed in Conan Center Index, or only update the getting started ?

**Comment by uilianries** [comment]
@danimtb please take a look https://github.com/conan-io/docs/pull/1505

**Comment by danimtb** [comment]
@uilianries As we don't want to move the packages to the new ones without user and channel, please update this PR moving the deployment example to the Poco reference **with** user and channel and keep the other examples as they are. Thanks!!

**Pull request merged**
