### PR TITLE
Update Folly version to CCI package

### LINKED ISSUE #52: [bug] Update folly example (binaries are not available for VS2019)
Binaries for `folly/basic` example are not available for VS 2019. This is something to fix, all the example should work out-of-the-box with mainstream compilers/versions

### PR DESCRIPTION
**Pull request by uilianries**
fixes #52

### CODE REVIEW

**Comment by uilianries** [comment]
This is an interesting situation.

Travis failed because libevent/2.1.11 was not found in Conan Center Index. Conan tried to find a regular package, gcc 5, release and static. The package id required is 74237cf67ca4e0327788fe9bfc4cbe98da3ce0fc.

https://travis-ci.org/github/conan-io/examples/jobs/675422297#L4596

However, if you search for it on Conan Center, you will get the package ID 4c20597a2710d74d4873bcbffc9c4e0ee32ae76b instead.

    conan search -r conan-center libevent/2.1.11@ -q "compiler=gcc AND compiler.version=5 AND build_type=Release AND shared=False"

```
Package_ID: 4c20597a2710d74d4873bcbffc9c4e0ee32ae76b
        [options]
            disable_threads: False
            fPIC: True
            shared: False
            with_openssl: True
        [settings]
            arch: x86_64
            build_type: Release
            compiler: gcc
            compiler.version: 5
            os: Linux
        Outdated from recipe: False
```

The problem actually comes from openssl/1.1.1d. Few days ago I sent [this PR](https://github.com/conan-io/conan-center-index/pull/1189) which removed 3 options for OpenSSL 1.1.1 (they are disabled according the upstream), so the package id for OpenSSL changed.

Now back to this situation, when libevent was build, it used the old OpenSSL 1.1.1d PID and now is outdated. Thus, when Folly asked for libevent, the PID required is based on the latest revision, which doesn't not contain those old options.

I think this problem can affect more packages, as OpenSSL is a popular package.

Should we rebuild ALL packages which requires OpenSSL 1.1.1?

Also, Could we remove any option once added to a recipe, or just raise a ConanInvalidConfiguration instead?

/cc @jgsogo @danimtb @SSE4

**Comment by uilianries** [comment]
Creating a new revision for libevent, it updates the package id:

https://github.com/conan-io/conan-center-index/pull/1368

https://c3i.jfrog.io/c3i/misc/logs/pr/1368/1/libevent/2.1.11/74237cf67ca4e0327788fe9bfc4cbe98da3ce0fc/

**Comment by jgsogo** [comment]
Hi!

It depends on the package_id_mode. With the default mode (`semver_direct_mode`) which is the one running in ConanCenter, the package ID of a consumer (`libevent`) is not affected by the packageID of the requirements (`openssl`). So, modifying the options in `openssl` won't make `libevent`-pkgID to change and the binary should be available.

If `libevent` packageID is missing, it is because `libevent` is using different set of settings, options, or different requirements to compute the package_id (or this example is running with a different package_id_mode)

**Comment by jgsogo** [comment]
Having a look at what has changed from one revision to another of `libevent` I see:

## Current revision:  `b22a55fcbec2e19572eb72e0b06a4245`

Package ID: `74237cf67ca4e0327788fe9bfc4cbe98da3ce0fc`

```
[settings]
    arch=x86_64
    build_type=Release
    compiler=gcc
    compiler.version=5
    os=Linux

[requires]
    openssl/1.Y.Z

[options]
    disable_threads=False
    fPIC=True
    shared=False
    with_openssl=True

[full_settings]
    arch=x86_64
    build_type=Release
    compiler=gcc
    compiler.version=5
    os=Linux

[full_requires]
    openssl/1.1.1d:76f87539fc90ff313e0b3182641a9bb558a717d2

[full_options]
    disable_threads=False
    fPIC=True
    shared=False
    with_openssl=True
    openssl:386=False
    openssl:fPIC=True
    openssl:no_asm=False
    openssl:no_async=False
    openssl:no_bf=False
    openssl:no_cast=False
    openssl:no_des=False
    openssl:no_dh=False
    openssl:no_dsa=False
    openssl:no_dso=False
    openssl:no_hmac=False
    openssl:no_md5=False
    openssl:no_mdc2=False
    openssl:no_rc2=False
    openssl:no_rsa=False
    openssl:no_sha=False
    openssl:no_sse2=False
    openssl:no_threads=False
    openssl:openssldir=None
    openssl:shared=False

[recipe_hash]
    d0fde5654c6ba6a3927beaf3bb7a8527

[env]
```

# Previous revision: `c7f14afb2b4d59828f7aa4ac20bcab79`

Package ID: `4c20597a2710d74d4873bcbffc9c4e0ee32ae76b`

```
[settings]
    arch=x86_64
    build_type=Release
    compiler=gcc
    compiler.version=5
    os=Linux

[requires]
    openssl/1.Y.Z

[options]
    disable_threads=False
    fPIC=True
    shared=False
    with_openssl=True

[full_settings]
    arch=x86_64
    build_type=Release
    compiler=gcc
    compiler.version=5
    os=Linux

[full_requires]
    openssl/1.1.1d:d5204605bf864d4bd98fc6a9e624938e8e04ad03
    zlib/1.2.11:76f87539fc90ff313e0b3182641a9bb558a717d2

[full_options]
    disable_threads=False
    fPIC=True
    shared=False
    with_openssl=True
    openssl:386=False
    openssl:fPIC=True
    openssl:no_asm=False
    openssl:no_async=False
    openssl:no_bf=False
    openssl:no_cast=False
    openssl:no_des=False
    openssl:no_dh=False
    openssl:no_dsa=False
    openssl:no_dso=False
    openssl:no_hmac=False
    openssl:no_md2=False
    openssl:no_md5=False
    openssl:no_mdc2=False
    openssl:no_rc2=False
    openssl:no_rc4=False
    openssl:no_rc5=False
    openssl:no_rsa=False
    openssl:no_sha=False
    openssl:no_sse2=False
    openssl:no_threads=False
    openssl:no_zlib=False
    openssl:openssldir=None
    openssl:shared=False
    zlib:fPIC=True
    zlib:minizip=False
    zlib:shared=False

[recipe_hash]
    c7f14afb2b4d59828f7aa4ac20bcab79

[env]

```

**Comment by uilianries** [comment]
The newest version of Openssl doesn't require zlib anymore, also the options `no_zlib`, `no_rc4`, `no_rc5` were removed.

**Comment by jgsogo** [comment]
Ok, I see it. The problem is that `zlib` was a requirement of `openssl` and it no longer is.

**Comment by uilianries** [comment]
But question is about rebuilding all packages which requires OpenSSL 1.1.1

**Comment by jgsogo** [comment]
I'm still thinking why this removes `zlib` from the requirements 🤕 

image

`if not None` -> `True`?

**Comment by jgsogo** [comment]
Oh! 🤦  There is another change in the recipe:

image

**Comment by uilianries** [comment]
The recipe is the same for all version, but only 1.1.1 doesn't require zlib anyone. That's why that workaround

**Comment by jgsogo** [comment]
Ok, back to the original problem. This introduces something we had never thought about. Up to know we knew that every time a new version arrives at ConanCenter it would be nice to upgrade the requirements of all the recipes to use that new version and avoid Conan reporting conflicts to beginners (different branches of your graph using different versions of zlib).

This introduces something else: any change of a recipe can modify the graph upwards and affect the package ID of the consumers (if they are public requirements) even for the a naïve package id mode like `semver_direct_mode`.

So any PR modifying the graph should trigger a new build for every recipe consuming it. This is something we cannot do by hand, this should be automated. 

Now we have conflicts and missing binaries in ConanCenter 😭

**Comment by uilianries** [comment]
That's bad. Well, I'll filter which packages requires OpenSSL 1.1.1 and submit a new PR for each one, updating the version. It should be enough for now, but we need to think in automatic solution in the future.

**Comment by uilianries** [comment]
Packages which need OpenSSL

```
./recipes/czmq/all/conanfile.py:        self.requires("openssl/1.1.1d")  # zdigest depends on openssl
./recipes/libcurl/all/conanfile.py:                self.requires.add("openssl/1.1.1f")
./recipes/libgit2/all/conanfile.py:            self.requires("openssl/1.1.1d")
./recipes/libgit2/0.27.x/conanfile.py:            self.requires("openssl/1.1.1d")
./recipes/librhash/all/conanfile.py:            self.requires("openssl/1.1.1d")
./recipes/libmysqlclient/all/conanfile.py:            self.requires.add("openssl/1.1.1d")
./recipes/sqlcipher/all/conanfile.py:            self.requires("openssl/1.1.1d")
./recipes/libssh2/all/conanfile.py:            self.requires.add("openssl/1.1.1d")
./recipes/opusfile/all/conanfile.py:        "openssl/1.1.1d"
./recipes/ixwebsocket/all/conanfile.py:            self.requires.add("openssl/1.1.1e")
./recipes/cpr/all/conanfile.py:            self.requires("openssl/1.1.1d")
./recipes/paho-mqtt-c/all/conanfile.py:            self.requires("openssl/1.1.1f")
./recipes/tgbot/all/conanfile.py:        "openssl/1.1.1d",
./recipes/libpq/all/conanfile.py:            self.requires.add("openssl/1.0.2s")
./recipes/jwt-cpp/all/conanfile.py:        self.requires("openssl/1.1.1d")
./recipes/poco/all/conanfile.py:            self.requires.add("openssl/1.0.2t")
./recipes/libressl/all/conanfile.py:        self.copy("openssl/*.h", dst="include", src=libressl_include_dir)
./recipes/folly/all/conanfile.py:        "openssl/1.1.1d",
./recipes/simple-websocket-server/all/conanfile.py:        "openssl/1.1.1d",
./recipes/botan/all/conanfile.py:            self.requires("openssl/1.0.2t")
./recipes/websocketpp/all/conanfile.py:        self.requires.add('openssl/1.1.1e')
./recipes/libarchive/all/conanfile.py:            self.requires.add("openssl/1.1.1d")
./recipes/libnghttp2/all/conanfile.py:            self.requires.add("openssl/1.1.1d")
./recipes/libtorrent/all/conanfile.py:            self.requires("openssl/1.1.1d")
./recipes/amqp-cpp/all/conanfile.py:            self.requires.add("openssl/1.1.1d")
./recipes/cpp-jwt/all/conanfile.py:        self.requires("openssl/1.1.1d")
./recipes/libevent/2.1.11/conanfile.py:            self.requires("openssl/1.1.1d")
./recipes/mysql-connector-c/all/conanfile.py:            self.requires.add("openssl/1.0.2u")
./recipes/cpp-httplib/all/conanfile.py:            self.requires.add("openssl/1.1.1d")
```

**Pull request merged**
