### PR TITLE
Run several Conan versions

### PR DESCRIPTION
**Pull request by jgsogo**
As we do with `hooks` this repo would benefit from running the examples using more that one Conan version.

This PR is adding:
 * Linux - Conan `develop` branch with py37 and py38
 * Linux - Conan `current` (`pip install conan`) with py37 and py38
 * Linux - Conan v1.21  with py37 and py38
 * Linux - Conan v1.20 with py37 and py38
 * Macos - Conan `develop` (py38) and Conan `current` (py37 and py38)

### CODE REVIEW

**Comment by uilianries** [comment]
@jgsogo The current error for python 3.5: 

> /usr/bin/ld: /tmp/3e91/.conan/data/glfw/3.3.1/bincrafters/stable/package/88e290eaa16812fc181613b516948b9051a2c9e1/lib/libglfw3.a(vulkan.c.o): undefined reference to symbol 'dlclose@@GLIBC_2.2.5'

Seems like the glibc version provided on that distro is incompatible. I see few options in this case, you could build all from sources, or run docker.

**Comment by jgsogo** [comment]
### Macos

`folly` example failing due to (probably more down the graph):

```
bzip2/1.0.6@conan/stable: WARN: Can't find a 'bzip2/1.0.6@conan/stable' package for the specified settings, options and dependencies:
- Settings: arch=x86_64, build_type=Release, compiler=apple-clang, compiler.version=11.0, os=Macos
- Options: build_executable=True, fPIC=True, shared=False
- Dependencies: 
- Package ID: 32bef4803d4b079e983ecb27f105881e778bc5a7
```

---

`protobuf` example failing due to:

```
protobuf/3.6.1@bincrafters/stable: WARN: Can't find a 'protobuf/3.6.1@bincrafters/stable' package for the specified settings, options and dependencies:
- Settings: arch=x86_64, build_type=Release, compiler=apple-clang, compiler.libcxx=libc++, compiler.version=11.0, os=Macos
- Options: fPIC=True, lite=False, shared=False, with_zlib=False
- Dependencies: 
- Package ID: eec6acc43f6348a597c20e5bd28d9e0590a02597
```

**Comment by jgsogo** [comment]
Windows
---


`folly` has a typo:

```python
folly/2018.11.12.00@bincrafters/stable: Downloaded recipe revision 0
ERROR: folly/2018.11.12.00@bincrafters/stable: Invalid configuration: Folly could not be built by Visual Studio < 14
```

the recipe:

```python
if self.settings.os == "Windows" and \
    self.settings.compiler == "Visual Studio" and \
    compiler_version < "15":
    raise ConanInvalidConfiguration("Folly could not be built by Visual Studio < 14")
```

----

Missing `openssl`:

```python
openssl/1.0.2t: WARN: Can't find a 'openssl/1.0.2t' package for the specified settings, options and dependencies:
- Settings: arch=x86, build_type=Release, compiler=Visual Studio, compiler.runtime=MD, compiler.version=14, os=Windows
- Options: 386=False, capieng_dialog=False, no_asm=False, no_async=False, no_bf=False, no_cast=False, no_des=False, no_dh=False, no_dsa=False, no_dso=False, no_hmac=False, no_md2=False, no_md5=False, no_mdc2=False, no_rc2=False, no_rc4=False, no_rc5=False, no_rsa=False, no_sha=False, no_sse2=False, no_threads=False, no_zlib=False, openssldir=None, shared=False, zlib:minizip=False, zlib:shared=False
- Dependencies: zlib/1.2.11
- Package ID: 5d34366328ff5fe8b9f93b912e5855ffb5fda596
ERROR: Missing prebuilt package for 'openssl/1.0.2t'
```

**Comment by uilianries** [comment]
I think we should update protobuf the newest version available, which is 3.9.1

**Comment by jgsogo** [comment]
Agree, and probably we should only use in this repo recipes that are in `conan-center-index`... but right now I only want this PR to pass  😭  (and probably we should reduce the number of appveyor jobs)

**Comment by jgsogo** [comment]
I'm merging this, although I really think we should reduce the number of jobs... but let's see how it works while using it

**Pull request merged**
