### PR TITLE
add deployment example

### PR DESCRIPTION
**Pull request by SSE4**
example for https://github.com/conan-io/docs/issues/1423 (https://github.com/conan-io/docs/pull/1431)
moved from https://github.com/SSE4/conan-deploy-tool

### CODE REVIEW

**Comment by danimtb** [comment]
This is not the example described there but a complete tool to deploy packages into different formats. I was asking about the specific script there and a full example using Conan packages

**Comment by SSE4** [comment]
@danimtb I've changed a little bit:
- example uses simple Poco-based MD5 project (https://docs.conan.io/en/latest/getting_started.html)
- use json generator to collect the information
- use custom script `deploy.py` to copy libraries
- use `makeself.io` to create a standalone archive
is it enough?

**Comment by SSE4** [comment]
CI error seems to be unrelated (different example fails):
```
Using lockfile: 'C:\projects\examples\features\lockfiles\ci\build_server_folder\release\conan.lock'
ERROR: Conanfile not found at C:\projects\examples\features\lockfiles\ci\build_server_folder\PkgB\0.1@user\testing:d813791f826f7718e6eefa5f8fe08d04861da163
********** Freeze dependencies in a lockfile ***********
```

**Comment by danimtb** [comment]
Yes, don't worry about the CI. It is an error that will be fixed in Conan 1.19.2.

This example is looking much better now. Please add it to the CI scripts and include a brief description and a link in the readme

**Comment by SSE4** [comment]
great, doing it now

**Pull request merged**
